name: sedaily_ai_nova
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  provider: ^6.1.5+1
  web: ^1.1.1
  go_router: ^16.2.1
  intl: ^0.19.0
  flutter_force_directed_graph: ^1.0.8
  dio: ^5.9.0
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  retrofit: ^4.7.2
  pretty_dio_logger: ^1.4.0
  logger: ^2.6.1
  retrofit_generator: ^10.0.5
  json_annotation: ^4.9.0
  vector_math: ^2.1.4
  url_launcher: ^6.3.2
  carousel_slider_plus: ^7.1.1
  hovering: ^1.0.4
  animated_text_kit: ^4.3.0
  fl_chart: ^1.1.1
  flutter_streaming_text_markdown: ^1.3.2
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.8.0
  vector_graphics_compiler: ^1.1.19


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/common/
    - assets/images/home/
    - assets/images/big_kinds/
    - assets/icons/
    - assets/icons/common/
    - assets/icons/home/
    - assets/icons/big_kinds/
    - assets/icons/ai_games/
    - assets/icons/ai_nexus/
    - assets/icons/ai_prism/
    - fonts/

    - path: assets/images/home/ai_nova_subtitle.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/images/home/ai_nexus_subtitle.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/images/home/ai_games_subtitle.svg
      transformers:
        - package: vector_graphics_compiler
    - path: assets/images/home/ai_prism_subtitle2.svg
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Black.otf
          weight: 900
        - asset: fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: fonts/Pretendard-Bold.otf
          weight: 700
        - asset: fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: fonts/Pretendard-Medium.otf
          weight: 500
        - asset: fonts/Pretendard-Regular.otf
          weight: 400
        - asset: fonts/Pretendard-Light.otf
          weight: 300
        - asset: fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: fonts/Pretendard-Thin.otf
          weight: 100